package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("petshop")
    void generatedTest() {
        step("open https://www.petshop.ru/", () -> {
            step("// todo: just add selenium action");
        });

        step("click on banner - clickable", () -> {
            step("// todo: just add selenium action");
        });

        step("click on sale - the price in the card is OK", () -> {
            step("// todo: just add selenium action");
        });

        step("check food for rats", () -> {
            step("// todo: just add selenium action");
        });

        step("check buy in one click", () -> {
            step("// todo: just add selenium action");
        });

        step("check unauthorized favorites (negative)", () -> {
            step("// todo: just add selenium action");
        });

        step("add goods to the cart", () -> {
            step("// todo: just add selenium action");
        });

        step("fill the purchase form", () -> {
            step("// todo: just add selenium action");
        });

        step("negative test for auto-purchase", () -> {
            step("// todo: just add selenium action");
        });

        step("negative test for unauthorized comment", () -> {
            step("// todo: just add selenium action");
        });

        step("check contacts for a particular shop", () -> {
            step("// todo: just add selenium action");
        });

        step("check vet drugstore (drop-down list)", () -> {
            step("// todo: just add selenium action");
        });

        step("check pop up maps", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.petshop.ru/'", () ->
            open("https://www.petshop.ru/"));

        step("Page title should have text 'Товары для животных, зоотовары онлайн, корма для домашних животных купить в интернет-магазине Petshop.ru'", () -> {
            String expectedTitle = "Товары для животных, зоотовары онлайн, корма для домашних животных купить в интернет-магазине Petshop.ru";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.petshop.ru/'", () ->
            open("https://www.petshop.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}